AGENCIES = [
    {
        "agency": "MTA",
        "city": "New York",
        "state": "NY",
        "platform": "mta_custom",
        "jobs_url": "https://careers.mta.org/",
    },
    {
        "agency": "LA Metro",
        "city": "Los Angeles",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/lametro",
    },
    {
        "agency": "CTA",
        "city": "Chicago",
        "state": "IL",
        "platform": "taleo",
        "jobs_url": "https://chicagotransit.taleo.net/careersection/inm/jobsearch.ftl",
    },
    {
        "agency": "NJ Transit",
        "city": "Newark",
        "state": "NJ",
        "platform": "salesforce_custom",
        "jobs_url": "https://njtransit.my.salesforce-sites.com/",
    },
    {
        "agency": "SFMTA",
        "city": "San Francisco",
        "state": "CA",
        "platform": "sf_careers",
        "jobs_url": "https://careers.sf.gov/",
        "department_id": "2297030",
    },
    {
        "agency": "WMATA",
        "city": "Washington",
        "state": "DC",
        "platform": "peoplesoft_wmata",
        "jobs_url": "https://careers.wmata.com/psc/careers/EXT_APPLICANT/HRMS/c/HRS_HRAM.HRS_CE.GBL?Action=A&HRS_PERSON_ID=0&SiteId=1&Page=HRS_CE_JOB_LST&PortalHostNode=CAREERS&PortalRegistryName=EXT_APPLICANT&PortalServletURI=https%3A%2F%2Fcareers.wmata.com%2Fpsp%2Fcareers%2F&PortalURI=https%3A%2F%2Fcareers.wmata.com%2Fpsc%2Fcareers%2F",
    },
    {
        "agency": "SEPTA",
        "city": "Philadelphia",
        "state": "PA",
        "platform": "successfactors",
        "jobs_url": "https://jobs.septa.org/",
    },
    {
        "agency": "MBTA",
        "city": "Boston",
        "state": "MA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/mbta",
    },
    {
        "agency": "King County Metro",
        "city": "Seattle",
        "state": "WA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/kingcounty?department[0]=MTD%20-%20Metro%20Transit",
    },
    {
        "agency": "RTC Transit",
        "city": "Las Vegas",
        "state": "NV",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/rtc",
    },
    {
        "agency": "BART",
        "city": "Oakland",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/bartca",
    },
    {
        "agency": "TriMet",
        "city": "Portland",
        "state": "OR",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/trimet",
    },
    {
        "agency": "Honolulu DTS",
        "city": "Honolulu",
        "state": "HI",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/honolulu?department[0]=Transportation%20Services",
    },
    {
        "agency": "AC Transit",
        "city": "Oakland",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/actransit",
    },
    {
        "agency": "RTD Denver",
        "city": "Denver",
        "state": "CO",
        "platform": "workday",
        "jobs_url": "https://rtddenver.wd5.myworkdayjobs.com/Careers",
    },
    {
        "agency": "MARTA",
        "city": "Atlanta",
        "state": "GA",
        "platform": "oracle",
        "jobs_url": "https://fa-evii-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs",
    },
    {
        "agency": "Sound Transit",
        "city": "Seattle",
        "state": "WA",
        "platform": "ukg",
        "jobs_url": "https://recruiting.ultipro.com/SOU1036SOUND/JobBoard/dcc5dbea-875e-4cd1-bfd2-8e046cecc54f/",
    },
]
