AGENCIES = [
    {
        "agency": "MTA",
        "city": "New York",
        "state": "NY",
        "platform": "mta_custom",
        "jobs_url": "https://careers.mta.org/search/jobs/in",
    },
    {
        "agency": "LA Metro",
        "city": "Los Angeles",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/lametro",
    },
    {
        "agency": "CTA",
        "city": "Chicago",
        "state": "IL",
        "platform": "taleo",
        "jobs_url": "https://chicagotransit.taleo.net/careersection/inm/jobsearch.ftl",
    },
    {
        "agency": "NJ Transit",
        "city": "Newark",
        "state": "NJ",
        "platform": "salesforce_custom",
        "jobs_url": "https://njtransit.my.salesforce-sites.com/",
    },
    {
        "agency": "SFMTA",
        "city": "San Francisco",
        "state": "CA",
        "platform": "sf_careers",
        "jobs_url": "https://careers.sf.gov/",
        "department_id": "2297030",
    },
    {
        "agency": "WMATA",
        "city": "Washington",
        "state": "DC",
        "platform": "peoplesoft_wmata",
        "jobs_url": "https://careers.wmata.com/psc/careers/EXT_APPLICANT/HRMS/c/HRS_HRAM.HRS_CE.GBL?Action=A&HRS_PERSON_ID=0&SiteId=1&Page=HRS_CE_JOB_LST&PortalHostNode=CAREERS&PortalRegistryName=EXT_APPLICANT&PortalServletURI=https%3A%2F%2Fcareers.wmata.com%2Fpsp%2Fcareers%2F&PortalURI=https%3A%2F%2Fcareers.wmata.com%2Fpsc%2Fcareers%2F",
    },
    {
        "agency": "SEPTA",
        "city": "Philadelphia",
        "state": "PA",
        "platform": "successfactors",
        "jobs_url": "https://jobs.septa.org/",
    },
    {
        "agency": "MBTA",
        "city": "Boston",
        "state": "MA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/mbta",
    },
    {
        "agency": "King County Metro",
        "city": "Seattle",
        "state": "WA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/kingcounty?department[0]=MTD%20-%20Metro%20Transit",
    },
    {
        "agency": "RTC Transit",
        "city": "Las Vegas",
        "state": "NV",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/rtc",
    },
    {
        "agency": "BART",
        "city": "Oakland",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/bartca",
    },
    {
        "agency": "TriMet",
        "city": "Portland",
        "state": "OR",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/trimet",
    },
    {
        "agency": "Honolulu DTS",
        "city": "Honolulu",
        "state": "HI",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/honolulu?department[0]=Transportation%20Services",
    },
    {
        "agency": "AC Transit",
        "city": "Oakland",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/actransit",
    },
    {
        "agency": "RTD Denver",
        "city": "Denver",
        "state": "CO",
        "platform": "workday",
        "jobs_url": "https://rtddenver.wd5.myworkdayjobs.com/Careers",
    },
    {
        "agency": "MARTA",
        "city": "Atlanta",
        "state": "GA",
        "platform": "oracle",
        "jobs_url": "https://fa-evii-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs",
    },
    {
        "agency": "Sound Transit",
        "city": "Seattle",
        "state": "WA",
        "platform": "ukg",
        "jobs_url": "https://recruiting.ultipro.com/SOU1036SOUND/JobBoard/dcc5dbea-875e-4cd1-bfd2-8e046cecc54f/",
    },
    {
        "agency": "Houston METRO",
        "city": "Houston",
        "state": "TX",
        "platform": "jobs2web",
        "jobs_url": "https://jobs.ridemetro.org/search/?q=&sortColumn=sort_title&sortDirection=asc",
    },
    {
        "agency": "Miami-Dade DTPW",
        "city": "Miami",
        "state": "FL",
        "platform": "peoplesoft_miami",
        "jobs_url": "https://jobs.miamidade.gov/",
    },
    {
        "agency": "DART",
        "city": "Dallas",
        "state": "TX",
        "platform": "workday",
        "jobs_url": "https://dart.wd1.myworkdayjobs.com/DART",
    },
    {
        "agency": "San Diego MTS",
        "city": "San Diego",
        "state": "CA",
        "platform": "adp",
        "jobs_url": "https://myjobs.adp.com/sandiegometro/cx/job-listing",
        "skip_scrape_reason": "ADP Playwright scraper crashes during full refresh; skipped to keep the run stable.",
    },
    {
        "agency": "Utah Transit Authority",
        "city": "Salt Lake City",
        "state": "UT",
        "platform": "uta_custom",
        "jobs_url": "https://careers.rideuta.com/search/jobs",
    },
    {
        "agency": "OCTA",
        "city": "Orange",
        "state": "CA",
        "platform": "workday",
        "jobs_url": "https://wd1.myworkdaysite.com/recruiting/octa/OCTA_Careers",
    },
    {
        "agency": "Valley Metro",
        "city": "Phoenix",
        "state": "AZ",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/valleymetro",
    },
    {
        "agency": "VTA",
        "city": "San Jose",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/vtasantaclara",
    },
    {
        "agency": "Metro Transit MN",
        "city": "Minneapolis",
        "state": "MN",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/metrocouncil?department[0]=Metro%20Transit",
    },
    {
        "agency": "Pace",
        "city": "Arlington Heights",
        "state": "IL",
        "platform": "oracle",
        "jobs_url": "https://iaymqy.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1",
    },
    {
        "agency": "Metra",
        "city": "Chicago",
        "state": "IL",
        "platform": "metra_custom",
        "jobs_url": "https://cta.cadienttalent.com/index.jsp?SHOWRESULTS=true&APPLICATIONNAME=MetraKTMDReqExt&SEARCHOBJECT=Posting&SOURCE=featuredjobs&locale=en_US&EVENT=com.deploy.application.ca.plugin.PostingSearch.doSearch&SEQ=postingSearchResults&",
    },
    {
        "agency": "Metrolink",
        "city": "Los Angeles",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/scrra",
    },
    {
        "agency": "Pittsburgh Regional Transit",
        "city": "Pittsburgh",
        "state": "PA",
        "platform": "prt_custom",
        "jobs_url": "https://careers.rideprt.org/",
    },
    {
        "agency": "VIA Metropolitan Transit",
        "city": "San Antonio",
        "state": "TX",
        "platform": "via_custom",
        "jobs_url": "https://css-viametro-prd.inforcloudsuite.com/hcm/Jobs/form/JobBoard%28VIA,EXTERNAL%29.JobSearchCompositeForm?navigation=JobBoard%28VIA,EXTERNAL%29.JobSearchCompositeFormNav&csk.JobBoard=EXTERNAL&csk.HROrganization=VIA&utm_source=Website_Employement_Page&utm_medium=Website&utm_campaign=Job_Clicks&utm_id=Employment_Jobs",
    },
    {
        "agency": "SacRT",
        "city": "Sacramento",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/sacrt",
    },
    {
        "agency": "LYNX",
        "city": "Orlando",
        "state": "FL",
        "platform": "dayforce",
        "jobs_url": "https://jobs.dayforcehcm.com/en-US/lynxdf/CANDIDATEPORTAL",
    },
    {
        "agency": "Palm Tran",
        "city": "West Palm Beach",
        "state": "FL",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/palmtran",
    },
    {
        "agency": "NICE Bus",
        "city": "Mineola",
        "state": "NY",
        "platform": "transdev",
        "jobs_url": "https://transdevna.jobs/jobs/?location=Garden+City%2C+NY",
    },
    {
        "agency": "SMART",
        "city": "Detroit",
        "state": "MI",
        "platform": "careersingovernment",
        "jobs_url": "https://www.careersingovernment.com/company/104716/suburban-mobility-authority-for-regional-transportation/",
    },
    {
        "agency": "Foothill Transit",
        "city": "West Covina",
        "state": "CA",
        "platform": "foothill_custom",
        "jobs_url": "https://www.foothilltransit.org/careers",
    },
    {
        "agency": "COTA",
        "city": "Columbus",
        "state": "OH",
        "platform": "applicantpro",
        "jobs_url": "https://cota.applicantpro.com/jobs/",
    },
    {
        "agency": "GCRTA",
        "city": "Cleveland",
        "state": "OH",
        "platform": "gcrta_custom",
        "jobs_url": "https://portal.gcrta.org/OA_HTML/OA.jsp?OAFunc=IRC_VIS_HOME_NEW_JOBS&_ti=308175068&oapc=2&oas=JzylrWhz8AZIUz1-YI9DaA..",
    },
    {
        "agency": "IndyGo",
        "city": "Indianapolis",
        "state": "IN",
        "platform": "adp",
        "jobs_url": "https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=45305ce8-e6fb-4092-9bd8-7f67b881b24c&ccId=19000101_000001&lang=en_US&selectedMenuKey=CurrentOpenings",
    },
    {
        "agency": "MCTS",
        "city": "Milwaukee",
        "state": "WI",
        "platform": "dayforce",
        "jobs_url": "https://jobs.dayforcehcm.com/en-US/mcts/CANDIDATEPORTAL",
    },
    {
        "agency": "Hampton Roads Transit",
        "city": "Norfolk",
        "state": "VA",
        "platform": "workday",
        "jobs_url": "https://gohrt.wd12.myworkdayjobs.com/HRT",
    },
    {
        "agency": "KCATA",
        "city": "Kansas City",
        "state": "MO",
        "platform": "adp",
        "jobs_url": "https://workforcenow.adp.com/jobs/apply/posting.html?client=KCATA&ccId=19000101_000001&type=MP&lang=en_US",
    },
    {
        "agency": "CATS",
        "city": "Charlotte",
        "state": "NC",
        "platform": "charlotte_custom",
        "jobs_url": "https://www.charlottenc.gov/CATS/Home/Featured-Content/Careers",
    },
    {
        "agency": "CapMetro",
        "city": "Austin",
        "state": "TX",
        "platform": "ukg",
        "jobs_url": "https://recruiting.ultipro.com/KEO1000KCS/JobBoard/ebca3ea8-05fd-4ab3-bb14-eb0406093310/?q=&o=postedDateDesc&w=&wc=&we=&wpst=",
    },
    {
        "agency": "GRTC",
        "city": "Richmond",
        "state": "VA",
        "platform": "adp",
        "jobs_url": "https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=974c82f1-1659-45b9-8e1e-81fb9814d7d4&ccId=19000101_000001&lang=en_US&source=CC2&selectedMenuKey=CareerCenter",
    },
    {
        "agency": "RTA New Orleans",
        "city": "New Orleans",
        "state": "LA",
        "platform": "rta_new_orleans_custom",
        "jobs_url": "https://www.norta.com/careers",
    },
    {
        "agency": "Metro Transit Madison",
        "city": "Madison",
        "state": "WI",
        "platform": "madison_custom",
        "jobs_url": "https://www.cityofmadison.com/metro/contact/jobs",
    },
    {
        "agency": "DDOT",
        "city": "Detroit",
        "state": "MI",
        "platform": "detroit_custom",
        "jobs_url": "https://detroitmi.gov/departments/human-resources-department/jobs",
    },
    {
        "agency": "SORTA Metro",
        "city": "Cincinnati",
        "state": "OH",
        "platform": "sorta_custom",
        "jobs_url": "https://www.go-metro.com/about-metro/careers",
    },
    {
        "agency": "PATH",
        "city": "Jersey City",
        "state": "NJ",
        "platform": "panynj_custom",
        "jobs_url": "https://www.jointheportauthority.com/jobs/search",
    },
    {
        "agency": "Caltrain",
        "city": "San Carlos",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/smctd",
        "filters": {"department": "Rail"},
    },
    {
        "agency": "Broward County Transit",
        "city": "Fort Lauderdale",
        "state": "FL",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/broward",
        "include_terms": ["transit", "transportation bus", "bus maint", "bus operations"],
    },
    {
        "agency": "HART",
        "city": "Tampa",
        "state": "FL",
        "platform": "adp",
        "jobs_url": "https://recruiting.adp.com/srccar/public/RTI.home?c=2174807&d=ExternalCareerSite",
    },
    {
        "agency": "PSTA",
        "city": "St. Petersburg",
        "state": "FL",
        "platform": "taleo_v2",
        "jobs_url": "https://phe.tbe.taleo.net/phe01/ats/careers/v2/searchResults?org=UH9TY5&cws=40",
    },
    {
        "agency": "Sun Tran",
        "city": "Tucson",
        "state": "AZ",
        "platform": "adp",
        "jobs_url": "https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=8c3a99b5-b7de-4618-af1d-4959eed15b34&ccId=19000101_000001&source=IN&lang=en_US&selectedMenuKey=CareerCenter",
    },
    {
        "agency": "Omnitrans",
        "city": "San Bernardino",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/omnitrans",
    },
    {
        "agency": "Riverside Transit Agency",
        "city": "Riverside",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/riversidetransit",
    },
    {
        "agency": "CDTA",
        "city": "Albany",
        "state": "NY",
        "platform": "cdta_custom",
        "jobs_url": "https://www.cdta.org/employment-opportunities",
    },
    {
        "agency": "NFTA",
        "city": "Buffalo",
        "state": "NY",
        "platform": "nfta_custom",
        "jobs_url": "https://jobs.nfta.com/",
    },
    {
        "agency": "Community Transit",
        "city": "Everett",
        "state": "WA",
        "platform": "icims",
        "jobs_url": "https://careers-commtrans.icims.com/jobs/search",
    },
    {
        "agency": "Spokane Transit Authority",
        "city": "Spokane",
        "state": "WA",
        "platform": "munis_selfservice",
        "jobs_url": "https://spokanetransitwa.munisselfservice.com/EmploymentOpportunities/Default.aspx",
    },
    {
        "agency": "Ben Franklin Transit",
        "city": "Richland",
        "state": "WA",
        "platform": "workday",
        "jobs_url": "https://bft.wd501.myworkdayjobs.com/Ben_Franklin_Transit_External_Careers",
    },
    {
        "agency": "Intercity Transit",
        "city": "Olympia",
        "state": "WA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/intercitytransit/",
    },
    {
        "agency": "Kitsap Transit",
        "city": "Bremerton",
        "state": "WA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/kitsaptransit",
    },
    {
        "agency": "Everett Transit",
        "city": "Everett",
        "state": "WA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/everettwa",
        "include_terms": ["Transit"],
    },
    {
        "agency": "Access Services",
        "city": "El Monte",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/accessla",
    },
    {
        "agency": "CalVans",
        "city": "Visalia",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://calvans.gov/careers/",
        "section_start": "Careers",
        "section_end": "Contact",
    },
    {
        "agency": "MTC",
        "city": "San Francisco",
        "state": "CA",
        "platform": "oracle",
        "jobs_url": "https://iazcqy.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs",
    },
    {
        "agency": "SJCOG",
        "city": "Stockton",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.sjcog.org/jobs/",
        "section_start": "Jobs",
        "section_end": "Steps",
    },
    {
        "agency": "SANDAG",
        "city": "San Diego",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/sandag",
    },
    {
        "agency": "LADOT",
        "city": "Los Angeles",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/lacity?department[0]=Transportation&sort=PositionTitle%7CAscending",
    },
    {
        "agency": "SamTrans",
        "city": "San Carlos",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/smctd",
        "include_terms": ["samtrans", "bus", "paratransit", "transit"],
        "exclude_terms": ["caltrain", "rail systems", "rail division"],
    },
    {
        "agency": "Victor Valley Transit Authority",
        "city": "Hesperia",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://vvta.org/careers/",
        "section_start": "Careers",
        "section_end": "Equal Opportunity",
    },
    {
        "agency": "Long Beach Transit",
        "city": "Long Beach",
        "state": "CA",
        "platform": "icims",
        "jobs_url": "https://careers-lbtransit.icims.com/jobs/search",
    },
    {
        "agency": "North County Transit District",
        "city": "Oceanside",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/nctd",
    },
    {
        "agency": "Monterey-Salinas Transit",
        "city": "Monterey",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://mst.org/about-mst/employment/",
        "section_start": "Employment",
        "section_end": "Equal Opportunity",
    },
    {
        "agency": "Big Blue Bus",
        "city": "Santa Monica",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/santamonica?department[0]=Santa%20Monica%20Department%20of%20Transportation&sort=PositionTitle%7CAscending",
    },
    {
        "agency": "Fresno Area Express",
        "city": "Fresno",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/fresnoca",
        "include_terms": ["fresno area express", "transit", "bus operator", "transportation", "fleet"],
    },
    {
        "agency": "County Connection",
        "city": "Concord",
        "state": "CA",
        "platform": "adp",
        "jobs_url": "https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=a728c770-548c-47c2-92a8-215ce09e89a9&ccId=19000101_000001&lang=en_US&selectedMenuKey=CareerCenter",
    },
    {
        "agency": "San Joaquin RTD",
        "city": "Stockton",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/sanjoaquinrtd",
    },
    {
        "agency": "StanisCruise",
        "city": "Modesto",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://staniscruise.com/",
        "section_start": "Careers",
        "section_end": "Contact",
    },
    {
        "agency": "Santa Cruz METRO",
        "city": "Santa Cruz",
        "state": "CA",
        "platform": "workday",
        "jobs_url": "https://scmtd.wd12.myworkdayjobs.com/METRO_Careers",
    },
    {
        "agency": "Golden Empire Transit District",
        "city": "Bakersfield",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/getbus",
    },
    {
        "agency": "Antelope Valley Transit Authority",
        "city": "Lancaster",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.avta.com/avta-employment-postings.php",
        "section_start": "Employment Postings",
        "section_end": "Get In Touch",
    },
    {
        "agency": "Santa Clarita Transit",
        "city": "Santa Clarita",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/santaclarita",
        "include_terms": ["transit", "transportation", "bus", "PTS"],
    },
    {
        "agency": "Montebello Bus Lines",
        "city": "Montebello",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/montebello",
        "include_terms": ["transit", "transportation", "bus", "mechanic"],
    },
    {
        "agency": "SBCTA",
        "city": "San Bernardino",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.gosbcta.com/about/jobs/",
        "section_start": "Careers",
        "section_end": "Contact",
    },
    {
        "agency": "Torrance Transit",
        "city": "Torrance",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/torranceca",
        "filters": {"department": "Transit"},
    },
    {
        "agency": "Gold Coast Transit District",
        "city": "Oxnard",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/gctd",
    },
    {
        "agency": "Golden Gate Transit",
        "city": "San Francisco",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/goldengate",
    },
    {
        "agency": "Marin Transit",
        "city": "San Rafael",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://marintransit.gov/jobs",
        "section_start": "Administrative Positions",
        "section_end": "Looking for a job as a bus driver",
    },
    {
        "agency": "Santa Barbara MTD",
        "city": "Santa Barbara",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://sbmtd.gov/careers/",
        "section_start": "Open positions",
        "section_end": "How to apply",
    },
    {
        "agency": "Kings Area Regional Transit",
        "city": "Hanford",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.kartbus.org/jobs",
        "section_start": "Jobs",
        "section_end": "Contact",
    },
    {
        "agency": "Anaheim Regional Transportation",
        "city": "Anaheim",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://rideart.org/careers/",
        "section_start": "Careers",
        "section_end": "Contact",
    },
    {
        "agency": "Sonoma County Transit",
        "city": "Santa Rosa",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/sonoma",
        "include_terms": ["sonoma county transit", "transit operator", "bus driver", "bus operator"],
    },
    {
        "agency": "LAVTA",
        "city": "Livermore",
        "state": "CA",
        "platform": "calopps",
        "jobs_url": "https://www.calopps.org/livermore-amador-valley-transit-authority",
    },
    {
        "agency": "Napa Valley Transportation Authority",
        "city": "Napa",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://nvta.ca.gov/about-nvta/nvta/careers/",
        "section_start": "Open Positions at NVTA",
        "section_end": "Equal Opportunity",
    },
    {
        "agency": "Tulare County Regional Transit Agency",
        "city": "Visalia",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/tulare",
        "filters": {"department": "Tulare County Regional Transit Agency"},
    },
    {
        "agency": "YoloTD",
        "city": "Woodland",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://yolotd.org/about-us/jobs/",
        "section_start": "Job Opportunities",
        "section_end": "Request for Information",
    },
    {
        "agency": "Placer County Transit/TART",
        "city": "Auburn",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/placer",
        "include_terms": ["transit", "bus", "TART", "transportation"],
    },
    {
        "agency": "Pomona Valley Transportation Authority",
        "city": "La Verne",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://pvtrans.org/about/employment/",
        "section_start": "Employment",
        "section_end": "Contact",
    },
    {
        "agency": "VCTC",
        "city": "Camarillo",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.goventura.org/work-with-vctc/jobs/",
        "section_start": "JOB OPPORTUNITIES",
        "section_end": "TRANSIT SERVICE OPPORTUNITIES",
    },
    {
        "agency": "Kern Regional Transit",
        "city": "Bakersfield",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/kernco",
        "include_terms": ["transit", "transportation", "bus", "kern regional"],
    },
    {
        "agency": "SLO RTA",
        "city": "San Luis Obispo",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.slorta.org/about-rta/employment/",
        "section_start": "Employment",
        "section_end": "Contact",
    },
    {
        "agency": "ICTC",
        "city": "El Centro",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.imperialctc.org/employment/",
        "section_start": "Employment",
        "section_end": "Contact",
    },
    {
        "agency": "RCTC",
        "city": "Riverside",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.rctc.org/employment/",
        "section_start": "Employment",
        "section_end": "Contact",
    },
    {
        "agency": "Visalia Transit",
        "city": "Visalia",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/visalia",
        "include_terms": ["transit", "transportation", "bus"],
    },
    {
        "agency": "Butte Regional Transit/B-Line",
        "city": "Chico",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.bcag.org/Employment/index.html",
        "section_start": "Employment",
        "section_end": "Contact",
    },
    {
        "agency": "WestCAT",
        "city": "Pinole",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://www.westcat.org/home/InsEmployment",
        "section_start": "Current Job Openings",
        "section_end": "Customer Care",
    },
    {
        "agency": "Unitrans",
        "city": "Davis",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://unitrans.ucdavis.edu/about/careers/",
        "section_start": "Careers",
        "section_end": "Contact",
    },
    {
        "agency": "Altamont Corridor Express",
        "city": "Stockton",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://acerail.com/about-ace/careers/",
        "section_start": "Careers",
        "section_end": "Contact",
    },
    {
        "agency": "Norwalk Transit",
        "city": "Norwalk",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/norwalkca",
        "include_terms": ["transit", "transportation", "bus"],
    },
    {
        "agency": "Santa Maria Regional Transit",
        "city": "Santa Maria",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/santamaria",
        "include_terms": ["transit", "transportation", "bus"],
    },
    {
        "agency": "Beach Cities Transit",
        "city": "Redondo Beach",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/redondo",
        "include_terms": ["transit", "transportation", "bus"],
    },
    {
        "agency": "Commerce Transit",
        "city": "Commerce",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/commerce",
        "include_terms": ["transit", "transportation", "bus"],
    },
    {
        "agency": "San Francisco Bay Ferry",
        "city": "San Francisco",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://weta.sanfranciscobayferry.com/employment",
        "section_start": "Employment",
        "section_end": "Contact",
    },
    {
        "agency": "Clean Air Express",
        "city": "Santa Barbara",
        "state": "CA",
        "platform": "static_text",
        "jobs_url": "https://cleanairexpress.com/",
        "section_start": "Employment",
        "section_end": "Contact",
    },
    {
        "agency": "La Mirada Transit",
        "city": "La Mirada",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/lamirada",
        "include_terms": ["transit", "transportation", "bus"],
    },
]
