AGENCIES = [
    {
        "agency": "LA Metro",
        "city": "Los Angeles",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/lametro",
    },
    {
        "agency": "BART",
        "city": "Oakland",
        "state": "CA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/bartca",
    },
    {
        "agency": "TriMet",
        "city": "Portland",
        "state": "OR",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/trimet",
    },
    {
        "agency": "MBTA",
        "city": "Boston",
        "state": "MA",
        "platform": "governmentjobs",
        "jobs_url": "https://www.governmentjobs.com/careers/mbta",
    },
    {
        "agency": "MTA",
        "city": "New York",
        "state": "NY",
        "platform": "mta_custom",
        "jobs_url": "https://careers.mta.org/",
    },
    {
        "agency": "CTA",
        "city": "Chicago",
        "state": "IL",
        "platform": "taleo",
        "jobs_url": "https://chicagotransit.taleo.net/careersection/inm/jobsearch.ftl",
    },
    {
        "agency": "SEPTA",
        "city": "Philadelphia",
        "state": "PA",
        "platform": "successfactors",
        "jobs_url": "https://jobs.septa.org/",
    },
    {
        "agency": "RTD Denver",
        "city": "Denver",
        "state": "CO",
        "platform": "workday",
        "jobs_url": "https://rtddenver.wd5.myworkdayjobs.com/Careers",
    },
    {
        "agency": "MARTA",
        "city": "Atlanta",
        "state": "GA",
        "platform": "oracle",
        "jobs_url": "https://fa-evii-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs",
    },
    {
        "agency": "Sound Transit",
        "city": "Seattle",
        "state": "WA",
        "platform": "ukg",
        "jobs_url": "https://recruiting.ultipro.com/SOU1036SOUND/JobBoard/dcc5dbea-875e-4cd1-bfd2-8e046cecc54f/",
    },
    {
        "agency": "NJ Transit",
        "city": "Newark",
        "state": "NJ",
        "platform": "salesforce_custom",
        "jobs_url": "https://njtransit.my.salesforce-sites.com/",
    },
]
